name: "Build Package"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Install Opus build dependencies"
      run: sudo apt-get install autoconf automake libtool gcc make

    - name: "wtf where did opus go"
      run: ls

    - name: "autoconf"
      run: ./opus/autoconf.sh

    - name: "configure"
      run: .opus//configure

    - name: "build opus"
      run: make ./opus

    - name: "help"
      run: cd ./opus && ls